### ISSUE TITLE
Google Play Store detection 

### ISSUE THREAD

**Issue by CHEF-KOCH** [ibuprophen1/SELinuxToggler#1]
Is there a way to bypass the Google Play Store detection?

You get an offer which tells you that this app is a risk (which is theoretically) correct. It#s pretty annoying especially if you re-flash a ROM.

**Comment by ibuprophen1** [comment]
That is called a PSA (Poisoned System Directories) warning from Google Play that warns users to uninstall various apps, especially, if they're SELinux-related ones. 

If you want, the following link has a nice little "how to" for Disabling those pesky "App is harmful" Security Alerts:

[URL="http://trackmyphones.com/b/disable-android-app-is-harmful-security-alert"]How to Disable the Android's (‘App is harmful’) Security Alert[/URL]

Please keep in mind that you can always let me know if you have any questions or concerns regarding The SELinux Toggler on the XDA Thread. 

Also, The SELinux Toggler will be [DISCONTINUED] within the next few days to make way for "The SELinux Switch" app. 

The primary reason is that I had rebuilt the whole app using a different Package Name. Currently The SELinux Toggler still uses "com.mrbimc.selinux" and The SELinux Switch uses "com.ibuprophen.selinux". It will still look and work the same since the app is simple and to the point... It didn't need to look any differently than before. It also has fixes, modifications and others to aid in compatibility. 

Just keep an eye out on The SELinux Toggler thread in XDA for the announcement of the new SELinux Switch thread. :-)
